//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CsharpAppiumTemplate.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CONFIG_GET_SCREENSHOT_FOR_EACH_STEP {
            get {
                return ((bool)(this["CONFIG_GET_SCREENSHOT_FOR_EACH_STEP"]));
            }
            set {
                this["CONFIG_GET_SCREENSHOT_FOR_EACH_STEP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("RelatorioTemplate")]
        public string CONFIG_REPORT_NAME {
            get {
                return ((string)(this["CONFIG_REPORT_NAME"]));
            }
            set {
                this["CONFIG_REPORT_NAME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int CONFIG_TIMEOUT_DEFAULT {
            get {
                return ((int)(this["CONFIG_TIMEOUT_DEFAULT"]));
            }
            set {
                this["CONFIG_TIMEOUT_DEFAULT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("qa")]
        public string CONFIG_ENVIRONMENT {
            get {
                return ((string)(this["CONFIG_ENVIRONMENT"]));
            }
            set {
                this["CONFIG_ENVIRONMENT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("127.0.0.1")]
        public string APPIUM_IP_ADDRESS {
            get {
                return ((string)(this["APPIUM_IP_ADDRESS"]));
            }
            set {
                this["APPIUM_IP_ADDRESS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4723")]
        public string APPIUM_PORT {
            get {
                return ((string)(this["APPIUM_PORT"]));
            }
            set {
                this["APPIUM_PORT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://127.0.0.1:4723/wd/hub")]
        public string APPIUM_SERVER {
            get {
                return ((string)(this["APPIUM_SERVER"]));
            }
            set {
                this["APPIUM_SERVER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("uiAutomator2")]
        public string APPIUM_AUTOMATION_NAME {
            get {
                return ((string)(this["APPIUM_AUTOMATION_NAME"]));
            }
            set {
                this["APPIUM_AUTOMATION_NAME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.15.1")]
        public string APPIUM_VERSION {
            get {
                return ((string)(this["APPIUM_VERSION"]));
            }
            set {
                this["APPIUM_VERSION"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Android")]
        public string ANDROID_PLATAFORM_NAME {
            get {
                return ((string)(this["ANDROID_PLATAFORM_NAME"]));
            }
            set {
                this["ANDROID_PLATAFORM_NAME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9.0.0")]
        public string ANDROID_PLATAFORM_VERSION {
            get {
                return ((string)(this["ANDROID_PLATAFORM_VERSION"]));
            }
            set {
                this["ANDROID_PLATAFORM_VERSION"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Pixel_3a_API_28")]
        public string ANDROID_DEVICE_NAME {
            get {
                return ((string)(this["ANDROID_DEVICE_NAME"]));
            }
            set {
                this["ANDROID_DEVICE_NAME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("app-debug.apk")]
        public string ANDROID_APP {
            get {
                return ((string)(this["ANDROID_APP"]));
            }
            set {
                this["ANDROID_APP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Chrome")]
        public string ANDROID_BROWSER_NAME {
            get {
                return ((string)(this["ANDROID_BROWSER_NAME"]));
            }
            set {
                this["ANDROID_BROWSER_NAME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("emulator-5554")]
        public string ANDROID_UDID {
            get {
                return ((string)(this["ANDROID_UDID"]));
            }
            set {
                this["ANDROID_UDID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ANDROID_NO_RESET {
            get {
                return ((bool)(this["ANDROID_NO_RESET"]));
            }
            set {
                this["ANDROID_NO_RESET"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ANDROID_FULL_RESET {
            get {
                return ((bool)(this["ANDROID_FULL_RESET"]));
            }
            set {
                this["ANDROID_FULL_RESET"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("com.amazonaws.devicefarm.android.referenceapp.Activities.MainActivity")]
        public string ANDROID_APP_ACTIVITY {
            get {
                return ((string)(this["ANDROID_APP_ACTIVITY"]));
            }
            set {
                this["ANDROID_APP_ACTIVITY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("com.amazonaws.devicefarm.android.referenceapp")]
        public string ANDROID_APP_PACKAGE {
            get {
                return ((string)(this["ANDROID_APP_PACKAGE"]));
            }
            set {
                this["ANDROID_APP_PACKAGE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PORTRAIT")]
        public string ANDROID_ORIENTATION {
            get {
                return ((string)(this["ANDROID_ORIENTATION"]));
            }
            set {
                this["ANDROID_ORIENTATION"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2A61B01CB2F947F18FDA9F44D6421XXX")]
        public string TEST_OBJECT_API_KEY {
            get {
                return ((string)(this["TEST_OBJECT_API_KEY"]));
            }
            set {
                this["TEST_OBJECT_API_KEY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://us1-manual.app.testobject.com/wd/hub")]
        public string TEST_OBJECT_URL {
            get {
                return ((string)(this["TEST_OBJECT_URL"]));
            }
            set {
                this["TEST_OBJECT_URL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8524B5F3-E529-4B09-8F05-EDE6040DDD65")]
        public string IOS_UDID {
            get {
                return ((string)(this["IOS_UDID"]));
            }
            set {
                this["IOS_UDID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("iOS")]
        public string IOS_PLATFORM_NAME {
            get {
                return ((string)(this["IOS_PLATFORM_NAME"]));
            }
            set {
                this["IOS_PLATFORM_NAME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12.2")]
        public string IOS_PLATFORM_VERSION {
            get {
                return ((string)(this["IOS_PLATFORM_VERSION"]));
            }
            set {
                this["IOS_PLATFORM_VERSION"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Amazon.AWSDeviceFarmiOSReferenceApp")]
        public string IOS_BUNDLE_ID {
            get {
                return ((string)(this["IOS_BUNDLE_ID"]));
            }
            set {
                this["IOS_BUNDLE_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IOS_NO_RESET {
            get {
                return ((bool)(this["IOS_NO_RESET"]));
            }
            set {
                this["IOS_NO_RESET"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IOS_FULL_RESET {
            get {
                return ((bool)(this["IOS_FULL_RESET"]));
            }
            set {
                this["IOS_FULL_RESET"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("XCUITest")]
        public string IOS_AUTOMATION_NAME {
            get {
                return ((string)(this["IOS_AUTOMATION_NAME"]));
            }
            set {
                this["IOS_AUTOMATION_NAME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("iPhone X")]
        public string IOS_DEVICE_NAME {
            get {
                return ((string)(this["IOS_DEVICE_NAME"]));
            }
            set {
                this["IOS_DEVICE_NAME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("myapp2.ipa")]
        public string IOS_APP {
            get {
                return ((string)(this["IOS_APP"]));
            }
            set {
                this["IOS_APP"] = value;
            }
        }
    }
}
